MODEL:


TRAIN:
  train_data_dir: [
    './dataset/lmdb/str/TextZoom/train1',
    './dataset/lmdb/str/TextZoom/train2',

    #'./dataset/SVT_lmdb/',

    #'./dataset/ICDAR2015_lmdb',  
        
  ]
  batch_size: 512
  width: 128
  height: 32
  epochs: 10000
  cuda: True
  ngpu: 1
  workers: 8
  resume: ''
  ckpt_dir: './ckpt/with_test'
  voc_type: 'all' #'digits lower upper all'
  saveInterval: 200
  displayInterval: 50 #display loss
  adadelta: False
  lr: 0.001
  adam: True
  optimizer: "Adam"
  beta1: 0.5
  manualSeed: 1234
  max_len: 100
  keep_ratio: False
  down_sample_scale: 2

  VAL:
    val_data_dir: [
      './dataset/lmdb/str/TextZoom/test/hard',
      './dataset/lmdb/str/TextZoom/test/easy',
      './dataset/lmdb/str/TextZoom/test/medium',

      #'./dataset/SVT_lmdb/',

      #'./dataset/ICDAR2015_lmdb',
      
    ]
    n_vis: 10
    vis_dir: 'demo'
    valInterval: 200 #-1, val at the end of epoch
    rec_pretrained: './dataset/demo.pth.tar'
    moran_pretrained: './dataset/moran.pth'
    crnn_pretrained: './dataset/crnn.pth'

TEST:
  checkpoint: ''
  test_data_dir: [
  ]

CONVERT:
  image_dir:
  lmdb_dir:
  n_convert: 10
